var navList = ['首页','公司简介','新闻动态','产品展示','联系我们'];
var introTitleList = ['公司简介','新闻动态','产品展示','联系我们'];
var proMenuList = ['客厅吸顶灯','客厅吊灯','餐厅吊灯','卧室灯','台灯','落地灯','壁灯','新中式配置'];

var news = [
    {"title":"新闻标题1","date":"2017-03-14","newsNum":"1","content":"新闻详细内容1"},
    {"title":"新闻标题2","date":"2017-03-14","newsNum":"2","content":"新闻详细内容2"},
    {"title":"新闻标题3","date":"2017-03-14","newsNum":"3","content":"新闻详细内容3"},
    {"title":"新闻标题4","date":"2017-03-14","newsNum":"4","content":"新闻详细内容4"},
    {"title":"新闻标题5","date":"2017-03-14","newsNum":"5","content":"新闻详细内容5"},
    {"title":"新闻标题6","date":"2017-03-14","newsNum":"6","content":"新闻详细内容6"},
    {"title":"新闻标题7","date":"2017-03-14","newsNum":"7","content":"新闻详细内容7"},
    {"title":"新闻标题8","date":"2017-03-14","newsNum":"8","content":"新闻详细内容8"},
    {"title":"新闻标题9","date":"2017-03-14","newsNum":"9","content":"新闻详细内容9"},
    {"title":"新闻标题10","date":"2017-03-14","newsNum":"10","content":"新闻详细内容10"},
    {"title":"新闻标题11","date":"2017-03-14","newsNum":"11","content":"新闻详细内容11"}
];


var products = [
    {"img":"img/c1.jpg","font":"客厅吸顶灯1","type":"0","proNum":"1","content":"<p>产品详情</p><img src='img/c1.jpg'>"},
    {"img":"img/c2.jpg","font":"客厅吸顶灯2","type":"0","proNum":"2","content":"<p>产品详情</p><img src='img/c2.jpg'>"},
    {"img":"img/c3.jpg","font":"客厅吸顶灯3","type":"0","proNum":"3","content":"<p>产品详情</p><img src='img/c3.jpg'>"},
    {"img":"img/c4.jpg","font":"客厅吸顶灯4","type":"0","proNum":"4","content":"<p>产品详情</p><img src='img/c4.jpg'>"},
    {"img":"img/c5.jpg","font":"客厅吸顶灯5","type":"0","proNum":"5","content":"<p>产品详情</p><img src='img/c5.jpg'>"},
    {"img":"img/c6.jpg","font":"客厅吸顶灯6","type":"0","proNum":"6","content":"<p>产品详情</p><img src='img/c6.jpg'>"},
    {"img":"img/c7.jpg","font":"客厅吸顶灯7","type":"0","proNum":"7","content":"<p>产品详情</p><img src='img/c7.jpg'>"},
    {"img":"img/c1.jpg","font":"客厅吸顶灯8","type":"0","proNum":"8","content":"<p>产品详情</p><img src='img/c1.jpg'>"},
    {"img":"img/c2.jpg","font":"客厅吸顶灯9","type":"0","proNum":"9","content":"<p>产品详情</p><img src='img/c2.jpg'>"},
    {"img":"img/c3.jpg","font":"客厅吸顶灯10","type":"0","proNum":"10","content":"<p>产品详情</p><img src='img/c3.jpg'>"},
    {"img":"img/c4.jpg","font":"客厅吊灯1","type":"1","proNum":"11","content":"<p>产品详情</p><img src='img/c4.jpg'>"},
    {"img":"img/c5.jpg","font":"客厅吊灯2","type":"1","proNum":"12","content":"<p>产品详情</p><img src='img/c5.jpg'>"},
    {"img":"img/c6.jpg","font":"客厅吊灯3","type":"1","proNum":"13","content":"<p>产品详情</p><img src='img/c6.jpg'>"},
    {"img":"img/c5.jpg","font":"客厅吊灯4","type":"1","proNum":"14","content":"<p>产品详情</p><img src='img/c5.jpg'>"},
    {"img":"img/c4.jpg","font":"客厅吊灯5","type":"1","proNum":"15","content":"<p>产品详情</p><img src='img/c4.jpg'>"},
    {"img":"img/c3.jpg","font":"客厅吊灯6","type":"1","proNum":"16","content":"<p>产品详情</p><img src='img/c3.jpg'>"},
    {"img":"img/c2.jpg","font":"客厅吊灯7","type":"1","proNum":"17","content":"<p>产品详情</p><img src='img/c2.jpg'>"},
    {"img":"img/c1.jpg","font":"客厅吊灯8","type":"1","proNum":"18","content":"<p>产品详情</p><img src='img/c1.jpg'>"},
    {"img":"img/c2.jpg","font":"客厅吊灯9","type":"1","proNum":"19","content":"<p>产品详情</p><img src='img/c2.jpg'>"},
    {"img":"img/c4.jpg","font":"客厅吊灯10","type":"1","proNum":"20","content":"<p>产品详情</p><img src='img/c4.jpg'>"},
    {"img":"img/c6.jpg","font":"客厅吊灯11","type":"1","proNum":"21","content":"<p>产品详情</p><img src='img/c6.jpg'>"},
    {"img":"img/c5.jpg","font":"客厅吊灯12","type":"1","proNum":"22","content":"<p>产品详情</p><img src='img/c5.jpg'>"},
    {"img":"img/c7.jpg","font":"餐厅吊灯1","type":"2","proNum":"23","content":"<p>产品详情</p><img src='img/c7.jpg'>"},
    {"img":"img/c6.jpg","font":"餐厅吊灯2","type":"2","proNum":"24","content":"<p>产品详情</p><img src='img/c6.jpg'>"},
    {"img":"img/c5.jpg","font":"餐厅吊灯3","type":"2","proNum":"25","content":"<p>产品详情</p><img src='img/c5.jpg'>"},
    {"img":"img/c4.jpg","font":"餐厅吊灯4","type":"2","proNum":"26","content":"<p>产品详情</p><img src='img/c4.jpg'>"},
    {"img":"img/c3.jpg","font":"餐厅吊灯5","type":"2","proNum":"27","content":"<p>产品详情</p><img src='img/c3.jpg'>"},
    {"img":"img/c3.jpg","font":"餐厅吊灯6","type":"2","proNum":"28","content":"<p>产品详情</p><img src='img/c3.jpg'>"},
    {"img":"img/c6.jpg","font":"餐厅吊灯7","type":"2","proNum":"29","content":"<p>产品详情</p><img src='img/c6.jpg'>"},
    {"img":"img/c1.jpg","font":"餐厅吊灯8","type":"2","proNum":"30","content":"<p>产品详情</p><img src='img/c1.jpg'>"},
    {"img":"img/c2.jpg","font":"餐厅吊灯9","type":"2","proNum":"31","content":"<p>产品详情</p><img src='img/c2.jpg'>"},
    {"img":"img/c3.jpg","font":"餐厅吊灯10","type":"2","proNum":"32","content":"<p>产品详情</p><img src='img/c3.jpg'>"},
    {"img":"img/c4.jpg","font":"餐厅吊灯11","type":"2","proNum":"33","content":"<p>产品详情</p><img src='img/c4.jpg'>"},
    {"img":"img/c5.jpg","font":"餐厅吊灯12","type":"2","proNum":"34","content":"<p>产品详情</p><img src='img/c5.jpg'>"},
    {"img":"img/c6.jpg","font":"卧室灯1","type":"3","proNum":"35","content":"<p>产品详情</p><img src='img/c6.jpg'>"},
    {"img":"img/c7.jpg","font":"卧室灯2","type":"3","proNum":"36","content":"<p>产品详情</p><img src='img/c7.jpg'>"},
    {"img":"img/c6.jpg","font":"卧室灯3","type":"3","proNum":"37","content":"<p>产品详情</p><img src='img/c6.jpg'>"},
    {"img":"img/c5.jpg","font":"卧室灯4","type":"3","proNum":"38","content":"<p>产品详情</p><img src='img/c5.jpg'>"},
    {"img":"img/c4.jpg","font":"卧室灯5","type":"3","proNum":"39","content":"<p>产品详情</p><img src='img/c4.jpg'>"},
    {"img":"img/c3.jpg","font":"卧室灯6","type":"3","proNum":"40","content":"<p>产品详情</p><img src='img/c3.jpg'>"},
    {"img":"img/c2.jpg","font":"卧室灯7","type":"3","proNum":"41","content":"<p>产品详情</p><img src='img/c2.jpg'>"},
    {"img":"img/c1.jpg","font":"卧室灯8","type":"3","proNum":"42","content":"<p>产品详情</p><img src='img/c1.jpg'>"},
    {"img":"img/c2.jpg","font":"卧室灯9","type":"3","proNum":"43","content":"<p>产品详情</p><img src='img/c2.jpg'>"},
    {"img":"img/c3.jpg","font":"卧室灯10","type":"3","proNum":"44","content":"<p>产品详情</p><img src='img/c3.jpg'>"},
    {"img":"img/c4.jpg","font":"卧室灯11","type":"3","proNum":"45","content":"<p>产品详情</p><img src='img/c4.jpg'>"},
    {"img":"img/c5.jpg","font":"卧室灯12","type":"3","proNum":"46","content":"<p>产品详情</p><img src='img/c5.jpg'>"},
    {"img":"img/c6.jpg","font":"卧室灯13","type":"3","proNum":"47","content":"<p>产品详情</p><img src='img/c6.jpg'>"},
    {"img":"img/c7.jpg","font":"卧室灯14","type":"3","proNum":"48","content":"<p>产品详情</p><img src='img/c7.jpg'>"},
    {"img":"img/c6.jpg","font":"台灯1","type":"4","proNum":"49","content":"<p>产品详情</p><img src='img/c6.jpg'>"},
    {"img":"img/c5.jpg","font":"台灯2","type":"4","proNum":"50","content":"<p>产品详情</p><img src='img/c5.jpg'>"},
    {"img":"img/c4.jpg","font":"台灯3","type":"4","proNum":"51","content":"<p>产品详情</p><img src='img/c4.jpg'>"},
    {"img":"img/c3.jpg","font":"台灯4","type":"4","proNum":"52","content":"<p>产品详情</p><img src='img/c3.jpg'>"},
    {"img":"img/c2.jpg","font":"台灯5","type":"4","proNum":"53","content":"<p>产品详情</p><img src='img/c2.jpg'>"},
    {"img":"img/c1.jpg","font":"台灯6","type":"4","proNum":"54","content":"<p>产品详情</p><img src='img/c1.jpg'>"},
    {"img":"img/c2.jpg","font":"台灯7","type":"4","proNum":"55","content":"<p>产品详情</p><img src='img/c2.jpg'>"},
    {"img":"img/c3.jpg","font":"台灯8","type":"4","proNum":"56","content":"<p>产品详情</p><img src='img/c3.jpg'>"},
    {"img":"img/c4.jpg","font":"台灯9","type":"4","proNum":"57","content":"<p>产品详情</p><img src='img/c4.jpg'>"},
    {"img":"img/c5.jpg","font":"台灯10","type":"4","proNum":"58","content":"<p>产品详情</p><img src='img/c5.jpg'>"},
    {"img":"img/c6.jpg","font":"台灯11","type":"4","proNum":"59","content":"<p>产品详情</p><img src='img/c6.jpg'>"},
    {"img":"img/c7.jpg","font":"台灯12","type":"4","proNum":"60","content":"<p>产品详情</p><img src='img/c7.jpg'>"},
    {"img":"img/c6.jpg","font":"台灯13","type":"4","proNum":"61","content":"<p>产品详情</p><img src='img/c6.jpg'>"},
    {"img":"img/c5.jpg","font":"落地灯1","type":"5","proNum":"62","content":"<p>产品详情</p><img src='img/c5.jpg'>"},
    {"img":"img/c4.jpg","font":"落地灯2","type":"5","proNum":"63","content":"<p>产品详情</p><img src='img/c4.jpg'>"},
    {"img":"img/c3.jpg","font":"落地灯3","type":"5","proNum":"64","content":"<p>产品详情</p><img src='img/c3.jpg'>"},
    {"img":"img/c2.jpg","font":"落地灯4","type":"5","proNum":"65","content":"<p>产品详情</p><img src='img/c2.jpg'>"},
    {"img":"img/c1.jpg","font":"落地灯5","type":"5","proNum":"66","content":"<p>产品详情</p><img src='img/c1.jpg'>"},
    {"img":"img/c2.jpg","font":"落地灯6","type":"5","proNum":"67","content":"<p>产品详情</p><img src='img/c2.jpg'>"},
    {"img":"img/c3.jpg","font":"落地灯7","type":"5","proNum":"68","content":"<p>产品详情</p><img src='img/c3.jpg'>"},
    {"img":"img/c4.jpg","font":"落地灯8","type":"5","proNum":"69","content":"<p>产品详情</p><img src='img/c4.jpg'>"},
    {"img":"img/c5.jpg","font":"落地灯9","type":"5","proNum":"70","content":"<p>产品详情</p><img src='img/c5.jpg'>"},
    {"img":"img/c6.jpg","font":"壁灯1","type":"6","proNum":"71","content":"<p>产品详情</p><img src='img/c6.jpg'>"},
    {"img":"img/c7.jpg","font":"壁灯2","type":"6","proNum":"72","content":"<p>产品详情</p><img src='img/c7.jpg'>"},
    {"img":"img/c6.jpg","font":"壁灯3","type":"6","proNum":"73","content":"<p>产品详情</p><img src='img/c6.jpg'>"},
    {"img":"img/c5.jpg","font":"壁灯4","type":"6","proNum":"74","content":"<p>产品详情</p><img src='img/c5.jpg'>"},
    {"img":"img/c4.jpg","font":"壁灯5","type":"6","proNum":"75","content":"<p>产品详情</p><img src='img/c4.jpg'>"},
    {"img":"img/c3.jpg","font":"壁灯6","type":"6","proNum":"76","content":"<p>产品详情</p><img src='img/c3.jpg'>"},
    {"img":"img/c2.jpg","font":"壁灯7","type":"6","proNum":"77","content":"<p>产品详情</p><img src='img/c2.jpg'>"},
    {"img":"img/c1.jpg","font":"壁灯8","type":"6","proNum":"78","content":"<p>产品详情</p><img src='img/c1.jpg'>"},
    {"img":"img/c2.jpg","font":"壁灯9","type":"6","proNum":"79","content":"<p>产品详情</p><img src='img/c2.jpg'>"},
    {"img":"img/c3.jpg","font":"壁灯10","type":"6","proNum":"80","content":"<p>产品详情</p><img src='img/c3.jpg'>"},
    {"img":"img/c4.jpg","font":"新中式配置1","type":"7","proNum":"81","content":"<p>产品详情</p><img src='img/c4.jpg'>"},
    {"img":"img/c5.jpg","font":"新中式配置2","type":"7","proNum":"82","content":"<p>产品详情</p><img src='img/c5.jpg'>"},
    {"img":"img/c6.jpg","font":"新中式配置3","type":"7","proNum":"83","content":"<p>产品详情</p><img src='img/c6.jpg'>"},
    {"img":"img/c7.jpg","font":"新中式配置4","type":"7","proNum":"84","content":"<p>产品详情</p><img src='img/c7.jpg'>"},
    {"img":"img/c6.jpg","font":"新中式配置5","type":"7","proNum":"85","content":"<p>产品详情</p><img src='img/c6.jpg'>"},
    {"img":"img/c5.jpg","font":"新中式配置6","type":"7","proNum":"86","content":"<p>产品详情</p><img src='img/c5.jpg'>"},
    {"img":"img/c4.jpg","font":"新中式配置7","type":"7","proNum":"87","content":"<p>产品详情</p><img src='img/c4.jpg'>"}
];

var introInf = "中式部落——传承经典、赋予新生 <br/>中式，是沉淀在记忆中的优雅繁复、古朴沉稳，是尊贵、亦然高冷而触不可及。中山古镇“中式部落灯饰”，秉承将中式文化带入新生代的理念，用简约传承优雅、留白而摈弃繁复。实木精雕细作、以工匠之心、敬畏之心致敬传统、开创新中式灯饰之风。 <br>中式部落灯饰，潜心研发，陆续推出100多款让人耳目一新的灯饰产品。涵盖吸顶灯、吊灯、落地灯、台灯等系列，全面满足了新中式风格装饰的灯具配套要求。 <br>中式部落灯饰，将“普通人用得起的中式”作为自己公司策略。一方面，坚持采用新的生产工艺、提升实木加工的效率，降低成本。另外，中式部落紧跟时代趋势，摈弃奢华、繁复，以简约、经典之风去满足更多普通人的中式装修需求。<br>中式部落灯饰，从创立伊始就坚持品牌化运作思路，建立起完善的品牌形象体系和优厚的加盟政策。中式部落，希望与更多合作伙伴携手，共享新中式灯饰市场的财富盛宴。";
var infoInf = "毕业设计：中式部落 <br>姓名：宁勃 <br>班级：13140B05 <br>学号：1314010444 <br>联系方式：176-0069-2769";